apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: bap-ce-apac
spec:
  type: team
  children: []


---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []


---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: welylau
spec:
  memberOf: [bap-ce-apac]

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: andyhood
spec:
  profile:
    displayName: Andy Hood
    email: andyhood@google.com
  memberOf: [bap-ce-apac]
  
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: joeywong
spec:
  memberOf: [bap-ce-apac]
