apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: bap-ce-apac
spec:
  type: team
  children: []


---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []


---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: andyhood
spec:
  type: internal
  memberOf: [bap-ce-apac]

  

