apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: bap-ce-apac
spec:
  type: team
  children: []


# ---
# # https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
# apiVersion: backstage.io/v1alpha1
# kind: Group
# metadata:
#   name: guests
# spec:
#   type: team
#   children: []


---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: welylau
spec:
  profile:
    displayName: Wely Lau
    email: welylau@google.com
  memberOf: [bap-ce-apac]

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: andyhood
spec:
  profile:
    displayName: Andy Hood
    email: andyhood@google.com
    picture: https://lh3.googleusercontent.com/a/ACg8ocJNlgfnwHZutJztZV3JmhLji-mwugzbigJKHpWtv6lk1I9HZ3o=s96-c-rg-br100
  memberOf: [bap-ce-apac]
  
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: joeywong
spec:
  profile:
    displayName: Joey Wong
    email: joeywong@google.com
  memberOf: [bap-ce-apac]

